version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm run disable-serverless-usage-tracking
  build:
    commands:
      - npm run deploy:cicd