name: Deploy

on:
  push:
    branches:
      -main

jobs:
  deploy_lambda:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - name: npm install
        env:
          CI: true
        run: 
          npm ci 